### Get unique Admin details
GET http://localhost:3000/admin/cmfyjunzi00025lgvzmat5ebo
Content-Type: application/json


### Create Admin
POST http://localhost:3000/admin/
Content-Type: application/json

{
  "name"  :  "Chris Babatunde",
  "email" :    "cris_bee@gmail.com",
  "role"  :   "Dispatcher",
  "password"  : "crisbe4all!"
}

### Passenger signup
POST http://localhost:3000/passenger/signup
Content-Type: application/json

{
  "name" : "Sakeeb Awwal",
  "phone": "0811234567",
  "email": "admin@gmail.com",
  "disabilityType": "Mobility",
  "accessibilityNeeds": "Wheelchair space ride",
  "password": "admin1234"
}


### Get user cmfzrbdpq00008efl5q55gmdx
GET http://localhost:3000/passenger/admin@gmail.com
Content-Type: application/json


### Passenger login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin1234q"
}